check for repo before running create_yum_image
If the current links under /repo/toss/ haven't been created or updated,
create_yum_image will fail or create an image for the wrong toss version.
That wastes a lot of time.

diff --git a/lustre-mud b/lustre-mud
--- a/lustre-mud
+++ b/lustre-mud
@@ -782,6 +782,13 @@ function bounce_sample_node {
 # so our cwd doesn't disappear when we umount and restart
 cd /root
 
+# verify links to the repo exist
+repo_rpm="/repo/toss/$(distro_version --major)/current/$(arch)/toss-release-${desired}*.rpm"
+if ! ls $repo_rpm ; then
+	error "$funcname: unable to create image, $repo_rpm does not exist"
+	exit 2
+fi
+
 # make sure we have current configs in place
 $DRYRUN ${PDSH_LONG} -g mgmt cfagent -K
 
