ensure pacemaker is stopped and retry power state changes
After "timeout systemctl stop pacemaker", run pcs cluster kill to
handle the case where systemctl stop timed out.  We want to ensure
pacemaker is dead so it doesn't hold up the primary mgmt reboot.

After a power off or power on, wait a few seconds and check state.
If power state is not desired, try power off or on again.
It's sometimes the case that power state changes fail; it's very
unusual for them to fail twice if something isn't severely broken.

diff --git a/lustre-mud b/lustre-mud
--- a/lustre-mud
+++ b/lustre-mud
@@ -580,21 +580,30 @@ function bounce_all_nodes {
 	local nodelist=$(nodeattr -q 'mds||oss')
 	log "${funcname}: stopping pacemaker (and lustre)"
 	$DRYRUN timeout --kill-after=10m 11m systemctl stop pacemaker
+	$DRYRUN pcs cluster kill
 
 	log "${funcname}: powering off all lustre servers"
 	$DRYRUN pm -g -0 'mds||oss'
 	sleep 2
 	if [ $(pm -g -q 'mds||oss' | awk '/off:/ {print $NF}') != $nodelist ]; then
-		error "${funcname}: failed to power off nodes $nodelist, proceed manually"
-		$DRYRUN exit 2
+		$DRYRUN pm -g -0 'mds||oss'
+		sleep 2
+		if [ $(pm -g -q 'mds||oss' | awk '/off:/ {print $NF}') != $nodelist ]; then
+			error "${funcname}: failed to power off nodes $nodelist, proceed manually"
+			$DRYRUN exit 2
+		fi
 	fi
 
 	log "${funcname}: powering on all lustre servers"
 	$DRYRUN pm -g -1 'mds||oss'
 	sleep 2
 	if [ $(pm -g -q 'mds||oss' | awk '/on:/ {print $NF}') != $nodelist ]; then
-		error "${funcname}: failed to power on nodes $nodelist, proceed manually"
-		exit 2
+		$DRYRUN pm -g -1 'mds||oss'
+		sleep 2
+		if [ $(pm -g -q 'mds||oss' | awk '/on:/ {print $NF}') != $nodelist ]; then
+			error "${funcname}: failed to power on nodes $nodelist, proceed manually"
+			exit 2
+		fi
 	fi
 
 	log "${funcname}: waiting for lustre servers to boot"
